name: Test Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Force XCode 11.3
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app

      - name: Build Test
        run: xcodebuild clean build -project Biinge.xcodeproj
