name: CD TestFlight

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build-and-deploy:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: echo "Test Release"

      - name: Deploy
        run: echo "Test Release"
