name: CD TestFlight

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'

jobs:
  build-and-deploy:
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v2

      - uses: yukiarrr/ios-build-action@v1.5.0
        with:
          project-path: Biinge.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          code-signing-identity: 'iPhone Developer'
          export-method: 'development'
          build-sdk: 'iOS 15.0'
          build-destination: 'generic/platform=iOS'
          team-id: ${{ secrets.TEAM_ID }}
